import os
import csv
from datetime import datetime
import json

class ReportGenerator:
    """
    Generates automated runway inspection reports based on detection data.
    Outputs the report in Markdown format.
    """
    
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_markdown_report(self, detections: list, inspector_name: str = "Automated Drone System"):
        """
        Generates a Markdown report from a list of detections.
        
        Args:
            detections (list): List of dictionaries containing detection details
                (e.g., class, confidence, risk_score, severity, bounding_box)
            inspector_name (str): Identifier for the system/person generating the report
            
        Returns:
            str: Path to the generated Markdown file
        """
        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H:%M:%S")
        filename = f"Runway_Inspection_{now.strftime('%Y%m%d_%H%M%S')}.md"
        filepath = os.path.join(self.output_dir, filename)
        
        # Summary statistics
        total_detections = len(detections)
        severity_counts = {'Critical': 0, 'Medium': 0, 'Low': 0}
        material_counts = {}
        
        for det in detections:
            sev = det.get('severity', 'Low')
            mat = det.get('class', 'Unknown')
            
            if sev in severity_counts:
                severity_counts[sev] += 1
            
            material_counts[mat] = material_counts.get(mat, 0) + 1

        # Build Markdown content
        lines = []
        lines.append(f"# Skyrecon: Daily Runway Inspection Report")
        lines.append(f"**Date:** {date_str}  ")
        lines.append(f"**Time:** {time_str}  ")
        lines.append(f"**Inspector:** {inspector_name}\n")
        
        lines.append(f"## Executive Summary")
        lines.append(f"The automated drone inspection system completed a sweep of the runway. "
                     f"A total of **{total_detections}** potential hazards were detected.")
        lines.append("")
        
        lines.append(f"### Severity Breakdown")
        lines.append(f"- 🔴 **Critical Hazards:** {severity_counts['Critical']}")
        lines.append(f"- 🟡 **Medium Hazards:** {severity_counts['Medium']}")
        lines.append(f"- 🟢 **Low Hazards:** {severity_counts['Low']}\n")
        
        lines.append(f"### Detected Materials")
        for mat, count in sorted(material_counts.items(), key=lambda x: x[1], reverse=True):
            lines.append(f"- **{mat}**: {count}")
        lines.append("\n---\n")
        
        lines.append(f"## Detailed Findings")
        if not detections:
            lines.append("*No hazards detected on the runway during this inspection.*")
        else:
            lines.append("| ID | Material | Confidence | Severity | Risk Score | Location (BBox) |")
            lines.append("|---|---|---|---|---|---|")
            
            # Sort detections by risk score descending
            sorted_detections = sorted(detections, key=lambda x: x.get('risk_score', 0), reverse=True)
            
            for idx, det in enumerate(sorted_detections, 1):
                mat = det.get('class', 'N/A')
                conf = f"{det.get('confidence', 0):.1%}"
                sev = det.get('severity', 'N/A')
                score = det.get('risk_score', 'N/A')
                bbox = det.get('bbox', [0,0,0,0])
                bbox_str = f"[{bbox[0]}, {bbox[1]}, {bbox[2]}, {bbox[3]}]"
                
                # Add emoji for severity
                if sev == 'Critical': sev_fmt = f"🔴 {sev}"
                elif sev == 'Medium': sev_fmt = f"🟡 {sev}"
                else: sev_fmt = f"🟢 {sev}"
                
                lines.append(f"| #{idx} | {mat} | {conf} | {sev_fmt} | {score}/100 | {bbox_str} |")

        lines.append("\n---\n")
        lines.append(f"*Report automatically generated by Skyrecon AI Orchestration System.*")

        # Write to file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
            
        return filepath

    def generate_csv_report(self, detections: list):
        """Generates a CSV report from a list of detections."""
        now = datetime.now()
        filename = f"Runway_Inspection_{now.strftime('%Y%m%d_%H%M%S')}.csv"
        filepath = os.path.join(self.output_dir, filename)
        
        headers = ['ID', 'Material', 'Confidence', 'Severity', 'Risk Score', 'BBox']
        
        with open(filepath, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(headers)
            for idx, det in enumerate(detections, 1):
                writer.writerow([
                    idx,
                    det.get('class', 'N/A'),
                    f"{det.get('confidence', 0):.4f}",
                    det.get('severity', 'N/A'),
                    det.get('risk_score', 'N/A'),
                    str(det.get('bbox', [0,0,0,0]))
                ])
                
        return filepath

if __name__ == "__main__":
    # Test cases representing data that would be produced by the AI + Hazard Scorer
    dummy_detections = [
        {'class': 'Metal', 'confidence': 0.95, 'risk_score': 97, 'severity': 'Critical', 'bbox': [100, 200, 300, 400]},
        {'class': 'Plastic', 'confidence': 0.82, 'risk_score': 55, 'severity': 'Medium', 'bbox': [500, 50, 600, 150]},
        {'class': 'Organic', 'confidence': 0.88, 'risk_score': 75, 'severity': 'Critical', 'bbox': [10, 10, 210, 210]},
        {'class': 'Plastic', 'confidence': 0.60, 'risk_score': 22, 'severity': 'Low', 'bbox': [300, 300, 320, 320]},
        {'class': 'Other', 'confidence': 0.45, 'risk_score': 15, 'severity': 'Low', 'bbox': [100, 100, 120, 120]}
    ]
    
    print("Testing Report Generator...")
    generator = ReportGenerator(output_dir="reports")
    report_path = generator.generate_markdown_report(dummy_detections)
    print(f"Report successfully generated at: {report_path}")
    
    # Read back to display
    with open(report_path, 'r', encoding='utf-8') as f:
        print("\n--- REPORT PREVIEW ---\n")
        # Handle Windows terminal charmap error for emojis
        print(f.read().encode('ascii', 'ignore').decode('ascii'))
        print("\n----------------------\n")
