# Generated by Django 4.2.7 on 2025-12-02 10:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("bbox", models.JSONField(default=dict)),
                ("label", models.CharField(db_index=True, max_length=100)),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "hazard_score",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "detections",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("model", models.CharField(max_length=100)),
                ("max_payload", models.FloatField(help_text="kg")),
                (
                    "home_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("MAINTENANCE", "Maintenance"),
                            ("LOST", "Lost"),
                        ],
                        default="INACTIVE",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "drones",
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mission_name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("altitude_m", models.FloatField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="core.drone",
                    ),
                ),
            ],
            options={
                "db_table": "flights",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("OPERATOR", "Drone Operator"),
                            ("ANALYST", "Data Analyst"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="core_user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="core_user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("altitude", models.FloatField(help_text="meters above ground")),
                ("velocity", models.FloatField(blank=True, help_text="m/s", null=True)),
                (
                    "heading",
                    models.FloatField(blank=True, help_text="degrees 0-360", null=True),
                ),
                (
                    "battery",
                    models.IntegerField(
                        blank=True, help_text="percentage 0-100", null=True
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="core.drone",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.flight",
                    ),
                ),
            ],
            options={
                "db_table": "telemetry",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Runway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("airport_code", models.CharField(max_length=10)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "centerline",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("length_m", models.FloatField(blank=True, null=True)),
                ("width_m", models.FloatField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "runways",
                "indexes": [
                    models.Index(
                        fields=["airport_code"], name="runways_airport_8fc67c_idx"
                    ),
                    models.Index(fields=["active"], name="runways_active_b657a2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NavigationPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "planned_path",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                ("constraints", models.JSONField(default=dict)),
                (
                    "optimization_metric",
                    models.CharField(default="time", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_plans",
                        to="core.drone",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.flight",
                    ),
                ),
            ],
            options={
                "db_table": "navigation_plans",
            },
        ),
        migrations.CreateModel(
            name="InferenceJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("frame_url", models.URLField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("detections_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("external_job_id", models.CharField(blank=True, max_length=255)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_jobs",
                        to="core.drone",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.flight",
                    ),
                ),
            ],
            options={
                "db_table": "inference_jobs",
            },
        ),
        migrations.CreateModel(
            name="Hazard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("reasoning", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_hazards",
                        to="core.user",
                    ),
                ),
                (
                    "detection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazard",
                        to="core.detection",
                    ),
                ),
            ],
            options={
                "db_table": "hazards",
            },
        ),
        migrations.AddIndex(
            model_name="drone",
            index=models.Index(fields=["identifier"], name="drones_identif_dd10dc_idx"),
        ),
        migrations.AddIndex(
            model_name="drone",
            index=models.Index(fields=["status"], name="drones_status_888221_idx"),
        ),
        migrations.AddIndex(
            model_name="drone",
            index=models.Index(fields=["last_seen"], name="drones_last_se_0e8378_idx"),
        ),
        migrations.AddField(
            model_name="detection",
            name="drone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="core.drone",
            ),
        ),
        migrations.AddField(
            model_name="detection",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.flight",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="telemetry",
            index=models.Index(
                fields=["drone", "timestamp"], name="telemetry_drone_i_d4a313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telemetry",
            index=models.Index(
                fields=["timestamp"], name="telemetry_timesta_98a6ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationplan",
            index=models.Index(fields=["drone"], name="navigation__drone_i_03ff3d_idx"),
        ),
        migrations.AddIndex(
            model_name="inferencejob",
            index=models.Index(fields=["status"], name="inference_j_status_2ddae1_idx"),
        ),
        migrations.AddIndex(
            model_name="inferencejob",
            index=models.Index(
                fields=["submitted_at"], name="inference_j_submitt_2aad0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hazard",
            index=models.Index(fields=["level"], name="hazards_level_e2ac49_idx"),
        ),
        migrations.AddIndex(
            model_name="hazard",
            index=models.Index(
                fields=["acknowledged"], name="hazards_acknowl_8aa0b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hazard",
            index=models.Index(fields=["archived"], name="hazards_archive_807895_idx"),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(
                fields=["drone", "start_time"], name="flights_drone_i_712d53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(fields=["status"], name="flights_status_69640c_idx"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["drone", "timestamp"], name="detections_drone_i_0cd7bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["timestamp"], name="detections_timesta_85bcbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["label"], name="detections_label_d29c80_idx"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["confidence"], name="detections_confide_2af26b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["hazard_score"], name="detections_hazard__3ad773_idx"
            ),
        ),
    ]
