# Generated by Django 4.2.7 on 2026-03-11 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("YOLO", "YOLOv8"),
                            ("PYTORCH", "PyTorch"),
                            ("TENSORFLOW", "TensorFlow"),
                        ],
                        default="YOLO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DEPLOYED", "Deployed"),
                            ("READY", "Ready"),
                            ("TRAINING", "Training"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="READY",
                        max_length=20,
                    ),
                ),
                ("accuracy", models.FloatField(default=0.0)),
                ("file_path", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Model",
                "db_table": "ai_models",
                "ordering": ["-created_at"],
            },
        ),
    ]
