# Generated by Django 4.2.7 on 2026-03-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_aimodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="file_path",
            field=models.FileField(blank=True, null=True, upload_to="models/"),
        ),
    ]
